spring.application.name=apimatricula
# formato fecha
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=America/Lima
#Data Source Properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/matricula
spring.datasource.username=root
spring.datasource.password=root

#JPA Properties
spring.jpa.database=MYSQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
