spring.application.name=mi-servidor-eureka
#server.port=8761
server.port=8762
eureka.instance.hostname=milocalhost
eureka.instance.prefer-ip-address=false
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka,http://milocalhost:8762/eureka

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.expected-client-renewal-interval-seconds=30
eureka.server.renewal-percent-threshold=0.85
